---
# Github
- src: git@github.com:Schmitzis/ansible_netcup_scripts.git
  name: netcup_scripts
  scm: git
- src: git@github.com:Schmitzis/ansible-keepalived.git
  name: keepalived
  version: feat-check-config
  scm: git
